[package]
name = "covtunes"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = "0.13.1"
rodio = "0.20.1"
cpal = "0.15.3"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
lto = true
